web:
 static_path: 
 port: 8080
 domain: 0.0.0.0
 read_timeout: 5
 write_timeout: 5
 idle_timeout: 5
gorm:
 debug: true
 db_type: mysql
 max_lifetime: 7200
 max_open_conns: 150
 max_idle_conns: 50
 table_prefix: tb_
mysql:
 port: 3306
 user: root
 password: root
 host: 127.0.0.1
 db_name: goapp
 parameters: charset=utf8&parseTime=True&loc=Asia%2FShanghai
sqlite3: 
 path: data/goapp.db
public:
 path: /home/developer/work_api/casbin_manage/upload/
app:
 appid: wxb3a2779799fec869
 secret: 974ed01aad8d5d731a9db8924d46c466
 grant_type: authorization_code
 token_grant_type: client_credential
 wx_url: https://api.weixin.qq.com/sns/jscode2session
 token_url: https://api.weixin.qq.com/cgi-bin/token
 content_check_url: https://api.weixin.qq.com/wxa/msg_sec_check
 image_check_url: https://api.weixin.qq.com/wxa/img_sec_check
images:
 path: /home/mhq/images/
 prefix_url: /images/
 default_img: default.jpg
log:
 file_path: logs
 file_name: back_api